### PR TITLE
Simpily api and hide impl

### PR DESCRIPTION
**Pull request by KrystilizeNevaDies**

### CODE REVIEW

**Review by Yu-Vitaqua-fer-Chronos — CHANGES_REQUESTED** [review]
Why are the dependencies put here? This is just the remapper/jar creator

**Comment by KrystilizeNevaDies** [comment]
That was in there for testing, I just forgot to remove it, my bad. I'll be available to fix it in about 5 hours, or you're welcome to merge this pr and remove it.

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
In this case we should also expose a method returning URLs from the Minecraft and related jars

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
> That was in there for testing, I just forgot to remove it, my bad. I'll be available to fix it in about 5 hours, or you're welcome to merge this pr and remove it.

Alright then, good to know

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Hm thinking about it, I don't think the implementation should be hidden, if someone needs more control for example

**Pull request merged**
